---
kind: Pod
apiVersion: v1
metadata:
  namespace: csi-app
  name: csi-nginx
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - image: nginx:latest
      name: nginx
      command: [ "sleep", "1000000" ]
      volumeMounts:
        - name: awsdisk01
          mountPath: "/mnt/data"
  imagePullSecrets:
    - name: repositorysecretkey
  volumes:
    - name: awsdisk01
      persistentVolumeClaim:
        claimName: pvc-02-awsdisk