---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-aws
spec:
  storageClassName: ocs-storagecluster-ceph-rbd
  dataSource:
    name: restore-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi