apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: csi-app
---
kind: Pod
apiVersion: v1
metadata:
  namespace: csi-app
  name: csi-nginx
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - image: nginx:latest
      name: nginx
      command: [ "sleep", "1000000" ]
      volumeMounts:
        - name: awsdisk01
          mountPath: "/mnt/data"
  imagePullSecrets:
    - name: repositorysecretkey
  volumes:
    - name: awsdisk01
      persistentVolumeClaim:
        claimName: pvc-aws
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: csi-app
  name: pvc-aws
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2-csi
---
#oc create secret docker-registry repositorysecretkey --docker-username=amitabhprasad --docker-password=a1319172 --docker-server=docker.io